framgialink: "https://www.facebook.com/FramgiaVietnam"
khanhlink: "http://www.facebook.com/khanhmata.dn"
nhatlink: "#"
nguyenlink: "https://www.facebook.com/thaonguyen.tran.7311352"
rubyrailslink: "http://www.railstutorial.org/"
nothing: "#"
remember_me: "1"
